version: '3.7'

services:
  #Base de datos MySQL
  db:
    container_name: mysql_c
    image: ${MYSQL_IMAGE}
    volumes:
    - type: volume
      source: drupaldatabase
      target: /var/lib/mysql
    environment:
      #Variables de entorno para las credenciales de mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - milocal
    #Conectar el servicio a fluent-bit para recolectar logs
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: bd.logs

  #Servidor web Nginx
  nginx:
    container_name: nginx_c
    image: ${NGINX_IMAGE}
    volumes:
    - type: volume
      source: staticfiles
      target: /var/www/html
    environment:
      NGINX_BACKEND_PORT: 9000
      NGINX_SERVER_NAME: localhost
      NGINX_BACKEND_HOST: php
      PROJECT_NAME: ${PROJECT_NAME}
    networks:
      - milocal
    ports:
     - 80:80
     - 443:443
    depends_on:
      - "php"
      - "fluentd"
    #Conectar el servicio a fluent-bit para recolectar logs
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: nginx.logs
 
  #Servicio php drupal + php-fpm
  php:
    container_name: drupal_c
    image: ${DRUPAL_IMAGE}
    volumes:
    - type: volume
      source: staticfiles
      target: /opt/drupal/web
    environment:
    #Variables de entorno para conectar drupal con la base de datos mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql_c
      MYSQL_PORT: 3306
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_BASE_DOMAIN: ${PROJECT_BASE_DOMAIN}
    networks:
      - milocal
    depends_on:
      - "db"
    #Conectar el servicio a fluent-bit para recolectar logs
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: drupal.logs
  
  #Fluent-bit, recolector y reenviador de registros.  
  fluentd:
    container_name: fluentd
    # Imagen específica de fluent-bit para Loki+Grafana
    image: amazon/aws-for-fluent-bit
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      # Fichero de configuración principal de fluent-bit
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - milocal
      
#Volúmenes para ficheros estáticos (Drupal y MySQL) 
volumes:
  staticfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/FluentDockerCloud/storage/files
      o: bind
  drupaldatabase:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/FluentDockerCloud/storage/files
      o: bind
#Red local
networks:
  milocal:
    driver: bridge

